"""
mailer.py - Send SMTP security alert email with attached JPEG.

Phase 2: AI Evidence Assessment section added to email body.
Reads ALL credentials from environment variables.
Never logs passwords. Falls back gracefully when not configured.
"""

import os
import smtplib
import ssl
from email.message import EmailMessage
from typing import Optional


def _cfg(key: str, default: str = "") -> str:
    return os.getenv(key, default).strip()


def _format_ai_section(
    ai_result: dict,
    retry_occurred: bool = False,
    original_score: Optional[int] = None,
    final_score: Optional[int] = None,
) -> str:
    """Build AI Evidence Assessment block for email body."""
    if not ai_result or ai_result.get("status") not in ("ok", "analyzed"):
        return "\nAI Evidence Assessment: Unavailable\n"

    score = ai_result.get("quality_score", 0)
    issues = ai_result.get("issues", [])
    summary = ai_result.get("context_summary", "")

    usable_label = "Useful Evidence" if score >= 60 else "Limited Evidence"
    issues_str = ", ".join(i.replace("_", " ").title() for i in issues if i != "none") or "None"

    block = f"""
─────────────────────────────────────────
AI EVIDENCE ASSESSMENT
─────────────────────────────────────────
Evidence Quality:   {score}/100
Status:             {usable_label}
Issues Detected:    {issues_str}

AI Context:
{summary}
"""
    if retry_occurred and original_score is not None and final_score is not None:
        block += f"""
Note: Tsukuyomi detected poor initial evidence (score: {original_score}/100)
and automatically selected a clearer security snapshot (final score: {final_score}/100).
"""

    block += "─────────────────────────────────────────\n"
    return block


def send_alert(
    *,
    incident_id: str,
    device_name: str,
    latitude: float,
    longitude: float,
    accuracy: float,
    captured_at: str,
    photo_path: str,
    ai_result: Optional[dict] = None,
    retry_occurred: bool = False,
    original_score: Optional[int] = None,
    final_score: Optional[int] = None,
) -> tuple[bool, str]:
    """
    Send a Tsukuyomi security alert email.
    Returns (success: bool, error_message: str).
    """
    smtp_host     = _cfg("SMTP_HOST")
    smtp_port_str = _cfg("SMTP_PORT", "587")
    smtp_user     = _cfg("SMTP_USERNAME")
    smtp_pass     = _cfg("SMTP_PASSWORD")
    smtp_from     = _cfg("SMTP_FROM") or smtp_user
    trusted_email = _cfg("TRUSTED_EMAIL")
    use_tls       = _cfg("SMTP_USE_TLS", "true").lower() != "false"

    missing = [k for k, v in {
        "SMTP_HOST": smtp_host,
        "SMTP_USERNAME": smtp_user,
        "SMTP_PASSWORD": smtp_pass,
        "TRUSTED_EMAIL": trusted_email,
    }.items() if not v]

    if missing:
        msg = f"SMTP not configured. Missing env vars: {', '.join(missing)}"
        print(f"[mailer] {msg}")
        return False, msg

    try:
        smtp_port = int(smtp_port_str)
    except ValueError:
        return False, f"SMTP_PORT is not a valid integer: {smtp_port_str!r}"

    maps_url = f"https://www.google.com/maps?q={latitude},{longitude}"

    ai_block = _format_ai_section(
        ai_result or {},
        retry_occurred=retry_occurred,
        original_score=original_score,
        final_score=final_score,
    )

    msg = EmailMessage()
    msg["Subject"] = "Tsukuyomi Security Alert — Protection Triggered"
    msg["From"]    = smtp_from
    msg["To"]      = trusted_email

    body = f"""TSUKUYOMI SECURITY ALERT

Protection has been triggered on:

  Device:      {device_name}
  Triggered:   {captured_at}

LAST KNOWN LOCATION
  Latitude:    {latitude}
  Longitude:   {longitude}
  Accuracy:    ±{accuracy:.1f} meters

  Open in Maps: {maps_url}
{ai_block}
A security snapshot is attached to this email.

This alert was generated by an owner-armed Tsukuyomi anti-theft prototype.
Incident ID: {incident_id}
"""
    msg.set_content(body)

    if os.path.exists(photo_path):
        with open(photo_path, "rb") as f:
            msg.add_attachment(
                f.read(),
                maintype="image",
                subtype="jpeg",
                filename=f"tsukuyomi_{incident_id}.jpg",
            )
    else:
        print(f"[mailer] Warning: photo not found at {photo_path}")

    try:
        context = ssl.create_default_context()
        if use_tls:
            with smtplib.SMTP(smtp_host, smtp_port, timeout=15) as server:
                server.ehlo()
                server.starttls(context=context)
                server.ehlo()
                server.login(smtp_user, smtp_pass)
                server.send_message(msg)
        else:
            with smtplib.SMTP_SSL(smtp_host, smtp_port, context=context, timeout=15) as server:
                server.login(smtp_user, smtp_pass)
                server.send_message(msg)

        print(f"[mailer] Alert sent to {trusted_email} for incident {incident_id}")
        return True, ""

    except Exception as exc:
        err = str(exc)
        print(f"[mailer] SMTP error for incident {incident_id}: {err}")
        return False, err
